# version: '3.8'

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile.dev
#     volumes:
#       - .:/src
#       - /src/node_modules
#     ports:
#       - "5173:5173"
#     command: npm run dev
#     environment:
#       - NODE_ENV=development
#       - PORT=5173